# Generated by Django 5.2.7 on 2025-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(default='3 Months', max_length=50)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('rating', models.FloatField(default=4.5)),
            ],
        ),
    ]
